version: '3.4'

services:
  passive.api:
    image: ${DOCKER_REGISTRY-}passiveapi
    depends_on:
        - "redis_server"
        - "postgres_server"
    build:
      context: .
      dockerfile: Passive.API/Dockerfile
    links:
        - "redis_server"
        - "postgres_server"

  redis_server:
    image: redis:latest
    container_name: redis_server
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  postgre_server:
    image: postgres:latest
    container_name: postgres_server
    ports:
        - "5432:5432"
    restart: always
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: AccessDB
        PGDATA: /data/postgres
    volumes:
        - db_volume:/data/postgres

volumes:
  db_volume: